### ISSUE TITLE
FontAwesome Kit Integration / Self Hosting FontAwesome Icons

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify#63]
FontAwesome Kits are currently not supported in React with the npm font awesome package. Either must find a workaround how to use locally embedded svgs by FontAwesome or must wait until feature is released.

FA Support stated that React Kit Support is on their feature timeline for the near future. We should keep an eye on that!

**Comment by m1212e** [comment]
Could you post a link to the relases page, changelog, etc. here so we have a reference?

**Comment by TadeSF** [comment]
Possible Workaround: https://jeroenpelgrims.com/custom-fontawesome-kit-icons-in-react/

**Comment by TadeSF** [comment]
The changelog can be found here:
https://fontawesome.com/docs/changelog/

**Comment by m1212e** [comment]
I agree. Yesterday I tried to help Robin setting up the project since he had some spare time and wanted to work on some issues, the font awesome license key thing is quite an annoyance regarding contributions of people we don't know and cannot give keys to. Maybe there is a way to do some kind of "proxies" when using those icons?

**Comment by m1212e** [comment]
https://github.com/DeutscheModelUnitedNations/munify/pull/168 will at least reduce our api calls

**Comment by TadeSF** [comment]
Solved in #169
